# fast-format-x configuration
# Update the tools below to match the formatters used in your repository.
# Use check_args for CI mode (ffx --all --check) to verify without modifying files.
version: 1

tools:
  # Web files: CSS, SCSS, Markdown, JSON, YAML, HTML
  # Prettier: the standard for web file formatting
  - name: prettier
    include:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.md'
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.yml'
      # - '**/*.html'
    exclude: ['public/**']
    cmd: npx
    args: [prettier, --write]
    check_args: [prettier, --check]
