# fast-format-x configuration
# Update the tools below to match the formatters used in your repository.
# Use check_args for CI mode (ffx --all --check) to verify without modifying files.
version: 1

tools:
  - name: prettier
    include: ['**/*.md', '**/*.yml', '**/*.yaml', '**/*.js', '**/*.ts']
    cmd: npx
    args: [prettier, --write]
    check_args: [prettier, --check]

  - name: rubocop
    include:
      - '**/*.rb'
      - '**/*.rake'
    exclude:
      - 'vendor/**'
    cmd: bundle
    args: [exec, rubocop, -A]
    check_args: [exec, rubocop]

  - name: ktlint
    include: ['**/*.kt', '**/*.kts']
    cmd: ktlint
    args: [-F]
    check_args: []

  - name: gofmt
    include: ['**/*.go']
    cmd: gofmt
    args: [-w]
    check_args: [-l]

  - name: rustfmt
    include: ['**/*.rs']
    cmd: cargo
    args: [fmt, --]
    check_args: [fmt, --, --check]
