baseURL = "https://briansigafoos.com"
languageCode = "en-us"
title = "Brian Sigafoos"

pygmentsCodeFences = true
pygmentsStyle = "native"

disqusShortname = "briansigafoos"
googleAnalytics = "UA-42740116-1"

[params]
  twitter = "https://twitter.com/BrianSigafoos"
  github = "https://github.com/BrianSigafoos"
  linkedin = "https://linkedin.com/in/sigafoos"
