baseURL = "https://briansigafoos.com"
languageCode = "en-us"
title = "Brian Sigafoos"

pygmentsCodeFences = true
pygmentsStyle = "native"

googleAnalytics = "UA-42740116-1"

[author]
  name = "Brian Sigafoos"
  email = "brian.sigafoos@gmail.com"

[params]
  about_path = "/about"
  source_code_url = "https://github.com/BrianSigafoos/hugo_site"
  disqusShortname = "briansigafoos"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
