# https://gohugo.io/hosting-and-deployment/hosting-on-github/
name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # TODO: revert
          hugo-version: '0.110.0'
          extended: true # Needed for SCSS processing

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm

      - name: Install JS packages
        run: npm ci
        shell: bash

      - run: hugo --minify

      # Only deploy on main branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: BrianSigafoos/briansigafoos.github.io
          publish_branch: main
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
